service:
  name: etirement-api
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  statement:
    handler: services/accounts/statement.handler
    events:
      - http:
          method: get
          path: statements
          cors: true
  banks:
    handler: services/banks/list.search
    events:
      - http:
          method: get
          path: banks
          cors: true
